title: Mazvita J Chimbadzwa
logo: "C:\Users\Pc\OneDrive\Pictures\mazvie.png"
description: An aspiring data analyst passionate about leveraging data analytics and artificial intelligence (AI) to enhance supply chain operations. 
show_downloads: true
theme: jekyll-theme-minimal
