title: Mazvita J Chimbadzwa
description: An aspiring data analyst passionate about leveraging data analytics and artificial intelligence (AI) to enhance supply chain operations. 
theme: jekyll-theme-minimal
